- src/handleQuery.ts
- src/routes/token/balances/evm.ts
- src/routes/token/holders/evm.ts
- src/routes/token/tokens/evm.ts
- src/routes/token/transfers/evm.ts
- Fix error handling
- new helper method `makeUsageQueryJson` to return pure JSON response (allows to inject data post query time)
- added `status:200` field to handle typed errors of `makeUsageQueryJson`
> add `makeUsageQueryJson` method

- src/mcp/tools.ts
- Hide `INFORMATION_SCHEMA`, `default`, `system`, `information_schema`
- Hide `.inner_id*` & `*_mv` & `backfill_*` (already was hidden)
> Reduce SHOW TABLES & SHOW DATABASE

- .github/workflows/ghcr.yml
- Dockerfile
- README.md
- bun.lock
- index.ts
- package.json
- src/config.ts
- src/logger.ts
- src/mcp/index.ts
- src/routes/version.ts
- src/sql/index.ts
```bash
docker build \
--build-arg GIT_COMMIT="$(git rev-parse HEAD)" \
--build-arg GIT_DATE="$(git log -1 --format=%cd --date=short)" \
--build-arg GIT_VERSION="$(git describe --tags --abbrev=0)" \
-t token-api .
```
```json
{"version":"v1.0.1","commit":"96ece84","date":"2025-03-23"}
```
> update app version build

- src/routes/networks.ts
- src/routes/token/balances/evm.ts
- src/routes/token/holders/evm.ts
- src/routes/token/tokens/evm.ts
- src/routes/token/transfers/evm.ts
- src/sql/balances_for_account/evm.sql
- src/sql/holders_for_contract/evm.sql
- src/sql/tokens_for_contract/evm.sql
- src/sql/transfers_for_account/evm.sql
- src/types/zod.ts
Ref: https://github.com/pinax-network/token-api/issues/27
- trim `symbol` string field
- add `transaction_id` field
- add `icon` field to example
- rename `total_supply` => `circulating_supply`
> fix output fields

- package.json
- src/config.ts
- src/inject/prices.sql
- src/inject/prices.tokens.ts
- src/inject/prices.ts
- src/inject/symbol.tokens.ts
- src/inject/symbol.ts
- src/routes/token/balances/evm.ts
- src/routes/token/holders/evm.ts
- src/routes/token/tokens/evm.ts
- src/routes/token/transfers/evm.ts
> Add additional network prices

- src/sql/ohlcv_prices_usd_for_contract/evm.sql
- Includes both directions for TOKEN/STABLE pairs
- Weighted average for open/close based on pair prices count
> Improve `ohlc` SQL

- src/inject/icon.ts
- src/inject/prices.tokens.ts
- src/inject/symbol.tokens.ts
- Add Unichain stable tokens
- Remove extra token metadata
> Add Unichain stable tokens

- src/routes/token/swaps/evm.ts
- src/sql/swaps/evm.sql
Fixes for swap performance issues
- Add DESC timestamp sorting to initial `swaps` SELECT
- Add `age` default filter (30 days, max 180 days)
> Fixes for swap performance issues

- src/routes/token/holders/evm.ts
- src/routes/token/swaps/evm.ts
- src/routes/token/transfers/evm.ts
- src/sql/holders_for_contract/evm.sql
- src/types/zod.ts
> Change to OrderDirection filter

- src/routes/token/pools/evm.ts
- src/routes/token/swaps/evm.ts
For `/pools/evm` and `/swaps/evm` endpoints
> Add missing `security` OpenAPI field

- src/routes/token/ohlc/prices/evm.ts
- src/sql/ohlcv_prices_for_pool/evm.sql
- src/sql/ohlcv_prices_usd_for_contract/evm.sql
Use new MV for faster and more accurate queries
> Refactor OHLCV by contract SQL

- src/routes/nft/collections_for_contract/evm.ts
- src/routes/nft/holders/evm.ts
- src/routes/nft/holders/index.ts
- src/routes/nft/index.ts
- src/routes/nft/ownerships_for_account/evm.ts
- src/sql/nft_holders/evm.sql
```    
┌─token_standard─┬─owner──────────────────────────────────────┬─quantity─┬─quantity_unique─┬─percentage─┬─network_id─┐
1. │ ERC721         │ 0x620b70123fb810f6c653da7644b5dd0b6312e4d8 │     3523 │            3523 │     0.3523 │ mainnet    │
2. │ ERC721         │ 0x29469395eaf6f95920e59f858042f0e28d98a20b │      217 │             217 │     0.0217 │ mainnet    │
3. │ ERC721         │ 0xaf184b4cbc73a9ca2f51c4a4d80ed67a2578e9f4 │      100 │             100 │       0.01 │ mainnet    │
4. │ ERC721         │ 0xc41a84d016b1391fa0f4048d37d3131988412360 │       87 │              87 │     0.0087 │ mainnet    │
5. │ ERC721         │ 0x000000001ee9baec2fd8676a913a3dfa2092ac6b │       79 │              79 │     0.0079 │ mainnet    │
6. │ ERC721         │ …
```
> Implement NFT holders

- src/routes/token/balances/evm.ts
- src/routes/token/historical/balances/evm.ts
- src/routes/token/holders/evm.ts
- src/routes/token/pools/evm.ts
- src/routes/token/swaps/evm.ts
- src/routes/token/tokens/evm.ts
- src/routes/token/transfers/evm.ts
- src/sql/ohlcv_prices_for_pool/evm.sql
Hotfix for token contracts metadata not being correct in new DB versions.
> Pin DB version for Token endpoints

- src/routes/token/balances/svm.ts
- src/sql/balances_for_account/svm.sql
Make `contract` alias for `mint` and add `program`.
> Fix response schema for SVM balances

- src/routes/token/transfers/svm.ts
- src/types/zod.ts
Typos and additional information for query parameters.
> Fix SVM endpoint OpenAPI descriptions

- src/routes/token/ohlc/pools/evm.ts
- src/routes/token/ohlc/prices/evm.ts
- src/sql/ohlcv_prices_for_pool/evm.sql
- src/sql/ohlcv_prices_usd_for_contract/evm.sql
Rework SQL for latest version of DB.
> Fix EVM OHLC endpoints

- src/sql/historical_balances_for_account/evm.sql
Use `COALESCE` for joining to include missing ETH native
> Fix EVM historical balances SQL

- src/routes/token/balances/evm.ts
- src/routes/token/holders/evm.ts
- src/routes/token/tokens/evm.ts
- src/sql/historical_balances_for_account/evm.sql
- src/sql/ohlcv_prices_for_pool/evm.sql
- src/sql/ohlcv_prices_for_pool/svm.sql
- src/sql/ohlcv_prices_usd_for_contract/evm.sql
For endpoints:
- `/balances/evm`
- `/holders/evm`
- `/tokens/evm`
> Fix OpenAPI endpoint response schemas

- src/routes/token/historical/balances/evm.ts
For endpoint `/historical/balances/evm`
> Fix `decimals` OpenAPI response type to number

- src/sql/swaps/evm.sql
> Add explicit String conversion for potential null string fields

- src/routes/token/pools/evm.ts
- src/sql/pools/evm.sql
This allows searching for specific token pairs.
Closes #157
> Replace `token` with `token0`/`token1` for EVM pools

- src/config.ts
- src/routes/token/ohlc/pools/evm.ts
`--ohlc-quantile` or `OHLC_QUANTILE` to set the min/max OHLC aggregation bins.
> Add OHLC min/max quantile to config

- bun.lock
- src/inject/symbol.ts
- src/routes/token/balances/evm.ts
- src/routes/token/historical/balances/evm.ts
- src/routes/token/transfers/evm.ts
- src/sql/pools/evm.sql
For addresses `0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee` and `0x0000000000000000000000000000000000000000`.
Inject symbol and name based on network ID.
> Inject native EVM symbols to API responses

- src/routes/token/balances/svm.ts
- src/sql/balances_for_account/svm.sql
- Rename `owner` to `account`
- Use CTE for filtering
> Update SVM Balances SQL

- src/routes/token/balances/svm.ts
- src/routes/token/transfers/svm.ts
- src/sql/balances_for_account/svm.sql
- src/sql/transfers/svm.sql
- src/types/zod.ts
New fields `name`, `symbol`, `uri` added to SVM Balances and Transfers.
> Add SVM metadata to tokens endpoints

- src/routes/token/index.ts
- src/routes/token/owner/index.ts
- src/routes/token/owner/svm.ts
- src/sql/owner_for_account/svm.sql
- Get owner address of an associated token account (ATA)
- Indicates if account has been closed or not
> Add SVM Owner by Associated Token Account
