- bun.lock
- package.json
- src/clickhouse/client.ts
- src/clickhouse/makeQuery.ts
- src/mcp/tools.ts
- src/mcp/utils.ts
- Switch query output format from `JSON` to `JSONEachRowWithProgress`
- Use MCP notifications to report on ClickHouse query progress (rows)
- Make ClickHouse query timeout same as MCP `fetch` (10 seconds)
> Support reporting CH query progress for MCP

- bun.lock
- package.json
- src/config.ts
- src/routes/health.ts
- src/routes/index.ts
- src/routes/networks.ts
- src/routes/token/balances/evm.ts
- src/routes/token/holders/evm.ts
- src/routes/token/transfers/evm.ts
- src/routes/version.ts
- src/sql/balances_for_account/evm.sql
- src/sql/holders_for_contract/evm.sql
- src/sql/transfers_for_account/evm.sql
- src/types/zod.spec.ts
- src/types/zod.ts
- add `/networks` endpoint
- includes `@pinax/graph-networks-registry` metadata
- add `--networks <string>` CLI param
- add `NETWORKS` env (defaults to "mainnet,bsc,base")
```json
{
"networks": [
{
"id": "mainnet",
"fullName": "Ethereum Mainnet",
"shortName": "Ethereum",
"networkType": "mainnet",
"nativeToken": "ETH",
"caip2Id": "eip155:1",
"icon": {
"web3Icons": {
"name": "ethereum"
}
},
"aliases": [
"ethereum",
"eth",
"eth-mainnet",
"evm-1"
]
}
]
}
```
> add `/networks` endpoint including @pinax/graph-networks-registry

- bun.lock
- package.json
- src/handleQuery.ts
- src/routes/token/balances/evm.ts
- src/routes/token/holders/evm.ts
- src/routes/token/index.ts
- src/routes/token/tokens/evm.ts
- src/routes/token/tokens/index.ts
- src/routes/token/transfers/evm.ts
- src/sql/tokens_for_contract/evm.sql
Includes:
- name/symbol/decimals
- holders (count all owners from  `balances_by_contract`)
- total_supply (sum all balances from  `balances_by_contract`)
Works pretty well, we could most likely expand to include `total_transfers` and also include logo images
> add `/tokens/evm` endpoint

- src/config.ts
- src/routes/networks.ts
- src/routes/token/balances/evm.ts
- src/routes/token/holders/evm.ts
- src/routes/token/tokens/evm.ts
- src/routes/token/transfers/evm.ts
- src/types/zod.spec.ts
- src/types/zod.ts
Auto discovery `networks` from 
```sql
SHOW DATABASES LIKE '%db_out'
```
store networks in memory, this is a workaround to avoid loading networks from the database on every request
```bash
2025-03-24 02:47:37.391 TRACE           1.0.0+559a0a8 (2025-03-23)      Supported networks:
[
'mainnet',
'arbitrum-one',
'base',
'bsc',
'optimism'
]
```
Removed `networkIdSchema` tests since this requires DB connection
> Auto detect networks

- .env.example
- README.md
- src/clickhouse/client.ts
- src/clickhouse/makeQuery.ts
- src/config.ts
- src/handleQuery.ts
- src/mcp/utils.ts
- src/routes/networks.ts
- src/routes/token/balances/evm.ts
- src/routes/token/holders/evm.ts
- src/routes/token/tokens/evm.ts
- src/routes/token/transfers/evm.ts
- Change `makeQuery` and `createClient` definitions to more broadly accept custom configuration
- New environment variable and CLI options:
- `MCP_USERNAME` / `--mcp-username`
- `MCP_PASSWORD` / `--mcp-password`
- `USERNAME` / `PASSWORD` not changed, still references the API DB user
- Update `.env` examples
> Use different DB user for MCP

- .env.example
- .vscode/settings.json
- src/config.ts
- src/inject/prices.ts
- src/mcp/tools.ts
- src/routes/networks.ts
- src/routes/token/balances/evm.ts
- src/routes/token/holders/evm.ts
- src/routes/token/index.ts
- src/routes/token/tokens/evm.ts
- src/routes/token/transfers/evm.ts
Auto-discovering networks from the database causes potential issues:
- When we start sinking new substreams package into `mainnet:evm-tokens@v1.10:db_out` for example we will have mutlitple "mainnet" databases and it will pick the first one which is wrong.
- while the database backfilling is still ongoing it will produce incomplete results 
- If new network support hasn't been officially announced yet we don't want people to auto-discover it while we are still working on it.
This PR returns "NETWORKS" env variable, i.e. `mainnet,bsc,base,arbitrum-one,optimism` and adds validation against database on start-up.
> Get list of networks from env variable

- .env.example
- README.md
- index.ts
- package.json
- src/banner.ts
- src/config.ts
- src/inject/prices.ts
- src/mcp/tools.ts
- src/routes/networks.ts
- src/routes/token/balances/evm.ts
- src/routes/token/holders/evm.ts
- src/routes/token/ohlc/prices/evm.ts
- src/routes/token/tokens/evm.ts
- src/routes/token/transfers/evm.ts
fixes: https://github.com/pinax-network/token-api/issues/44
- Add `.env` & CLI support for different Database Suffixes for EVM/SVM(Solana)/Antelope
- Allow disabling OpenAPI servers, this allows the Swagger UI to use the current hostname+port as server
```env
DB_EVM_SUFFIX=evm-tokens@v1.9.0:db_out
DB_SVM_SUFFIX=svm-tokens@v1.0.0:db_out
DB_ANTELOPE_SUFFIX=antelope-tokens@v1.0.0:db_out
DISABLE_OPENAPI_SERVERS=false
```
> Update `.env` for OpenAPI Server & `DB_EVM_SUFFIX`

- src/clickhouse/client.ts
- src/handleQuery.ts
Previously the API would return 404 on database timeout since no rows where returned in the result.
This fix will return 500 if the elapsed query time statistic is above the `MAX_EXECUTION_TIME` threshold defined in the client config.
> Return 500 on database execution timeout

- package.json
- src/handleQuery.ts
- src/sql/swaps/evm.sql
- src/sql/transfers/evm.sql
- Remove `FINAL` from token joins
- Add filtering to joined tables - reduced number of rows read 2-10x when filtering by `pool` and `contract`
- Explicitly list column in selects to minimize reads
> Optimize swaps and transfers queries

- src/handleQuery.ts
Instead of returning 404 with message and status code when there is no results for a query, return a 200 with empty `data` array in response.
**Before**
```json
{
"status": 404,
"code": "not_found_data",
"message": "No data found"
}
```
**After**
```json
{
"data": [],
"statistics": {
"bytes_read": 110134179,
"rows_read": 1745869,
"elapsed": 0.123360055
},
"pagination": {
"previous_page": 1,
"current_page": 1,
"next_page": 1,
"total_pages": 1
},
"results": 0,
"total_results": 0,
"request_time": "2025-05-05T18:22:53.248Z",
"duration_ms": 300
}
```
> Return empty data array instead of 404

- src/routes/nft/activities/evm.ts
Cannot use `any` when at least one of the two is specified.
> Fix using `any` with `from`/`to` parameters

- src/banner.ts
- src/config.ts
- src/inject/prices.ts
- src/mcp/tools.ts
- src/routes/networks.ts
- src/routes/nft/activities/evm.ts
- src/routes/nft/collections_for_contract/evm.ts
- src/routes/nft/holders/evm.ts
- src/routes/nft/items/evm.ts
- src/routes/nft/ownerships_for_account/evm.ts
- src/routes/nft/sales/evm.ts
- src/routes/token/balances/evm.ts
- src/routes/token/historical/balances/evm.ts
- src/routes/token/holders/evm.ts
- src/routes/token/ohlc/pools/evm.ts
- src/routes/token/ohlc/prices/evm.ts
- src/routes/token/pools/evm.ts
- src/routes/token/swaps/evm.ts
- src/routes/token/tokens/evm.ts
- src/routes/token/transfers/evm.ts
Use 3 new config parameters for handling databases:
- `DBS_TOKEN`
- `DBS_NFT`
- `DBS_UNISWAP`
This allows for having different networks with different databases names and versions instead of a single default one for all.
**Example**
```env
DBS_TOKEN=mainnet:evm-tokens@v1.14.0;arbitrum-one:evm-tokens@v1.11.0:db_out
DBS_NFT=mainnet:evm-nft-tokens@v0.5.1;optimism:evm-nft-tokens@v0.5.1
DBS_UNISWAP=mainnet:evm-uniswaps@v0.1.5;bsc:evm-uniswaps@v0.1.5
```
> Refactor database config handling

- src/sql/ohlcv_prices_usd_for_contract/evm.sql
Add `FINAL` so that `contracts` subqueries don't return more than one result
> Prevent OHLC prices subquery from returning more than one result

- src/mcp/tools.ts
The database naming convention isn't explicit when receiving the output from the `list_databases` tool.
Adds a field with the full name of the database to help the LLM.
> Add full database name in output of MCP tool

- src/routes/token/pools/evm.ts
- src/sql/pools/evm.sql
Endpoint can return a list of pools metadata (ordered by most recently created) but couldn't be paginated through.
Add `page` and `limit` parameters back.
> Fix missing pagination parameters for pools metadata endpoint

- src/sql/nft_sales/evm.sql
Adding Solana address to the list was throwing that error from the database.
Add a String conversion to fix.
> Fix `Too Large String` error for NFT sales

- src/sql/historical_balances_for_account/evm.sql
- src/sql/nft_activities/evm.sql
- src/sql/nft_sales/evm.sql
- src/sql/ohlcv_prices_for_pool/evm.sql
- src/sql/ohlcv_prices_for_pool/svm.sql
- src/sql/ohlcv_prices_usd_for_contract/evm.sql
- src/sql/swaps/evm.sql
- src/sql/swaps/svm.sql
- src/sql/transfers/evm.sql
- src/sql/transfers/svm.sql
- src/types/zod.spec.ts
- src/types/zod.ts
This fixes remaining issues of weird UNIX timestamp parsing between Javascript and ClickHouse
> Revert to parsing `timestamp` as number and as UInt64 in SQL

- src/sql/swaps/evm.sql
If pool data is missing from the `pool` table, a `JOIN` would return empty rows.
Fix by using `LEFT JOIN` to at least return the swap data.
> Fix missing EVM swaps in response by using `LEFT JOIN`

- src/routes/nft/activities/evm.ts
- src/routes/nft/collections_for_contract/evm.ts
- src/routes/nft/holders/evm.ts
- src/routes/nft/items/evm.ts
- src/routes/nft/ownerships_for_account/evm.ts
- src/routes/nft/sales/evm.ts
- src/routes/token/balances/evm.ts
- src/routes/token/balances/svm.ts
- src/routes/token/historical/balances/evm.ts
- src/routes/token/holders/evm.ts
- src/routes/token/holders/svm.ts
- src/routes/token/ohlc/pools/evm.ts
- src/routes/token/ohlc/pools/svm.ts
- src/routes/token/ohlc/prices/evm.ts
- src/routes/token/pools/evm.ts
- src/routes/token/pools/svm.ts
- src/routes/token/swaps/evm.ts
- src/routes/token/swaps/svm.ts
- src/routes/token/tokens/evm.ts
- src/routes/token/tokens/svm.ts
- src/routes/token/transfers/evm.ts
- src/routes/token/transfers/svm.ts
- src/utils.ts
Turn this:
```
example: {
data: ...
}
```
Into this:
```
examples: {
example: {
value: {
data: ...
}
}
}
```
> Reformat `examples` for OpenAPI to show up in Scalar

- src/clickhouse/client.ts
- src/config.ts
- src/handleQuery.ts
- src/logger.ts
- src/routes/health.ts
- New `--degraded-db-response-time` or `DB_RESPONSE_TIME_TRIGGER_MS` config option with default of 1s
- Check for DB response time by default and skip endpoint testing
- Use `skip_endpoints=false` for testing default endpoint queries response time
- Returns health state for database and API separately
> Improve health endpoint to test for DB and endpoints status

- src/sql/pools/evm.sql
`0x0000000000000000000000000000000000000000` is missing in `erc20_metadata_initialize`.
Add `if` statements to inject native values.
> Fix EVM native token metadata for `/pools` endpoints

- src/sql/balances_for_account/evm.sql
- src/sql/balances_for_account/svm.sql
- src/sql/historical_balances_for_account/evm.sql
- src/sql/holders_for_contract/evm.sql
- src/sql/holders_for_contract/svm.sql
- src/sql/nft_activities/evm.sql
- src/sql/nft_holders/evm.sql
- src/sql/nft_ownerships_for_account/evm.sql
- src/sql/nft_ownerships_for_account_with_sales/evm.sql
- src/sql/nft_sales/evm.sql
- src/sql/nft_transfers_for_address/evm.sql
- src/sql/nft_transfers_for_collection/evm.sql
- src/sql/ohlcv_prices_for_pool/evm.sql
- src/sql/ohlcv_prices_for_pool/svm.sql
- src/sql/ohlcv_prices_usd_for_contract/evm.sql
- src/sql/pools/evm.sql
- src/sql/pools/svm.sql
- src/sql/swaps/evm.sql
- src/sql/swaps/svm.sql
- src/sql/transfers/evm.sql
- src/sql/transfers/svm.sql
This avoids casting errors on the ClickHouse side.
In-line with the max value for `page`.
> Parse `limit` and `offset` as UInt64 in SQL

- src/handleQuery.ts
- src/utils.ts
Don't catch database timeout from `elapsed` statistics but from database error message.
> Handle database timeout issue from error message

- src/handleQuery.ts
Re-implement removed timeout handling from #206 but add check for data being empty as well.
> Add back timeout handling from empty data response

- src/routes/token/balances/svm.ts
- src/sql/balances_for_account/svm.sql
- Refactor `accounts` CTE for directly using variable substitution if provided
- Add `mints` CTE and filter for `balances` to improve performance
- Rename add `last_update_` prefix to `block_num`, `datetime` and `timestamp` for clarity
> Improve SQL performance for SVM Balances by Owner
